server:
  port: 8088

mybatis:
  type-aliases-package: indi.ZH.OfficialWeb.entity
  mapper-locations: classpath:persistence/xml/*/*.xml



pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/OfficialWeb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    templateEncoding: UTF-8
    template-loader-path: classpath:/templates



